<!-- define preset PHP variables -->
<?php $pagefile = "index"; $pagetitle = "Home"; ?>

<!DOCTYPE html>
<html lang="en">
    <!-- include HEAD tag -->
    <?php include "assets/html/head.php" ?>
    
    <!-- body tag — display loading if URL variable for loading authentication is set to true -->
    <body <?php if(isset($_GET["loading_auth"]) && $_GET["loading_auth"] == "true") { echo "class='loading_auth'"; } ?>>
        <!-- loading box if authentication is loading -->
        <div class="loading_auth_container default_style_loading_container">
            <div class="default_style_loading_loader"></div>
        </div>

        <!-- include navbar -->
        <?php include "assets/html/nav.php" ?>

        <!-- site content and container DIV -->
        <div class="container">
            <div class="col">
                <!-- landing page (left side) with catchy header, text, and login button -->
                
                <!-- catchy header (HTML is generated by PHP function) -->
                <h1 class="default_style_catchy_header header">
                    <?php echo generateCatchyHeaderHTML("Share your thoughts on our work."); ?>
                </h1>
                <p class="animated" style="opacity: 0;"><?php include "assets/txt/site_title.txt"; ?> is a platform for students to voice their concerns and suggest solutions to the issues faced by the student body. This platform allows students to make their voices heard, to pitch in on innovative ideas, and bring about lasting change to <?php  include "assets/txt/school_name.txt"; ?>.</p>
                <!-- note that this login button simply triggers the other login button -->
                <button class="login_alias animated" style="opacity: 0;">Sign in with Google</button>
            </div>
            <!-- this side includes an animated design with a circle of people, all connected by a singular idea. -->
            <div class="col">
                <div class="design animated" style="opacity: 0;">
                    <!-- display and write HTML elements for 8 people icons dynamically with PHP -->
                    <?php
                    (function(){
                        $number_of_icons = 8;
                        $internal_angle = 360 / $number_of_icons;

                        // get icons for both male and female icons and put in array
                        $gender_icons = array_map(function($gender) { return file_get_contents("assets/img/" . $gender . "_person_icon.svg"); }, ["male", "female"]);

                        for ($i = 0; $i < $number_of_icons; $i++) {
                            // get icon with random gender
                            $icon = $gender_icons[$i % 2];

                            // display icon, with transition delay, CSS variables for the angle, parametric x value variable --> cos(angle), and parametric y value variable --> sin(angle)
                            echo "<div class='person_icon' style='--transition-delay:", 0.2 + (0.2 * $i), "s; --angle: ", $internal_angle * $i, "deg; --parametric-val-x: ", cos(deg2rad($internal_angle * $i)), "; --parametric-val-y: ", sin(deg2rad($internal_angle * $i)), ";'>", $icon, "</div>";
                        }

                        // display lightbulb icon in center, symbolizing people connected by a singular idea
                        echo '<div class="idea_icon" style="transition-delay: ', 0.5 + (0.2 * ($i - 1)), 's">';
                        include "assets/img/idea_icon.svg";
                        echo "</div>";
                    })();
                    ?>
                </div>
            </div>
        </div>

        <!-- include footer -->
        <?php include "assets/html/footer.php" ?>

        <!-- include scripts -->
        <?php include "assets/html/scripts.php" ?>
    </body>
</html>
