<!-- define preset PHP variables -->
<?php $pagefile = "submit"; $pagetitle = "Create a Post"; ?>

<!DOCTYPE html>
<html lang="en">
    <!-- include HEAD tag -->
    <?php include "assets/html/head.php" ?>
    <body>
        <!-- include navbar -->
        <?php include "assets/html/nav_auth.php" ?>

        <!-- site content and container DIV -->
        <div class="container">
            <div class="block">
                <!-- first row includes just the header -->
                <div class="row">
                    <!-- catchy header (HTML is generated by PHP function) -->
                    <h1 class="default_style_catchy_header header">
                        <?php
                        echo generateCatchyHeaderHTML("Create a Post");
                        ?>
                    </h1>

                    <!-- this is the second header, which is shown after a proposal has been submitted -->
                    <h1 class="default_style_catchy_header header" style="display: none;">
                        <?php
                        echo generateCatchyHeaderHTML("Thanks for Submitting!");
                        ?>
                    </h1>
                </div>
                
                <!-- second row is split into two columns — the description, and the actual submission form -->
                <div class="row">
                    <!-- animated (in) description -->
                    <div class="col description animated" style="opacity: 0;">
                        <p style="margin-bottom: 1.5rem;"><strong>Note:</strong> Your post must first be approved by admin before it is shown to users.</p>
                    </div>
                
                    <!-- submission form -->
                    <div class="col form animated" style="opacity: 0;">
                        <!-- title box -->
                        <input type="text" class="title" placeholder="Write a title..." spellcheck="false">
                        
                        <!-- description box -->
                        <textarea placeholder="Write a detailed description..." spellcheck="false"></textarea>
                        
                        <!-- submit button with "Submit Anonymously" checkbox -->
                        <div class="button_container">
                            <button>Submit for Approval</button>
                            <div class="submit_anon_checkbox checkbox">
                                <input type="checkbox" name="submit_anonymously_checkbox" id="submit_anonymously_checkbox">
                                <label for="submit_anonymously_checkbox"></label>
                                <label for="submit_anonymously_checkbox" class="text">Submit Anonymously</label>
                            </div>
                            <div class="post_is_vote checkbox">
                                <input type="checkbox" name="is_vote_box" id="is_vote_box">
                                <label for="is_vote_box"></label>
                                <label for="is_vote_box" class="text">Make This Post a For/Against Vote</label>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- third row is shown after a proposal has been submitted, and contains extra description and text about
                the submission process -->
                <div class="row animated" style="display: none; opacity: 0;">
                    <p>Your proposal has been submitted for approval by admin. <a href="home.php">Back To Home &rarr;</a></p>
                </div>
            </div>
        </div>

        <!-- include footer -->
        <?php include "assets/html/footer.php" ?>

        <!-- include scripts -->
        <?php include "assets/html/scripts.php" ?>
    </body>
</html>